// Per-path cheatsheets — a <=1-page recall card for someone who COMPLETED a
// strategy learning path. Each is FORMULA + SOURCE-LOCATION pairs so a graduate
// can execute the strategy on a real filing/chart WITHOUT our tool. Bilingual.
// Generated from the curriculum-audit drafts; keyed by strategy id.
import type { Locale } from "./i18n";

export interface Cheatsheet {
  /** strategy id (matches STRATEGIES / practice route) */
  id: string;
  title: string;
  what: Record<Locale, string>;
  steps: Record<Locale, string[]>;
  data: Record<Locale, string[]>;
  rules: Record<Locale, string[]>;
  pitfall: Record<Locale, string>;
}

export const CHEATSHEETS: Record<string, Cheatsheet> = {
  "index-passive": {
    id: "index-passive",
    title: "Index / Passive (Own-the-Market)",
    what: { en: "Buy the whole market cheaply through a broad low-cost index fund/ETF and hold for decades — the evidence-based default for anyone who doesn't want to (or can't reliably) beat the market.", ko: "광범위 저비용 인덱스 펀드/ETF로 시장 전체를 싸게 사서 수십 년 보유 — 시장을 이길 자신이 없는 대다수 투자자에게 근거가 가장 탄탄한 기본 전략." },
    steps: { en: ["Pick your 'market': total-market (VTI) or S&P 500 (VOO) for US; a KOSPI200/total-market ETF (e.g. 069500) for KR. Decide stock/bond mix by your years-to-goal (~80–90% stocks when young, glide to ~40–50% near retirement).", "Open the fund/ETF page or prospectus and READ the expense ratio (labeled Expense Ratio / TER / 총보수·보수율). Reject anything above your ceiling.", "Choose the ACCOUNT before the fund: capture any employer match (US 401k), then tax-advantaged wrappers (US: 401k/IRA/Roth; KR: ISA / 연금저축 / IRP), then a plain brokerage/위탁계좌.", "Deploy the money: if you have a lump sum you can invest today, invest it now (it wins ~2/3 of the time); if cash arrives per paycheck, auto-invest each one as it lands (DCA by necessity — always good).", "Set two written rules: a max expense ratio you'll never cross, and lump-sum-vs-DCA — and be honest whether you chose DCA for the math or just to sleep.", "Automate, then do nothing: don't panic-sell in drawdowns, don't chase last year's winner. Rebalance to target ~once a year. De-risk (more bonds/cash) as the goal nears."], ko: ["'시장'을 고른다: 미국은 전체시장(VTI) 또는 S&P500(VOO), 한국은 KOSPI200/전체시장 ETF(예: 069500). 목표까지 남은 기간으로 주식/채권 비중 결정(젊을 땐 약 80~90% 주식, 은퇴 가까우면 약 40~50%로).", "펀드/ETF 상세 페이지나 투자설명서를 열어 보수율(Expense Ratio / TER / 총보수)을 직접 읽는다. 상한선을 넘으면 거른다.", "펀드보다 계좌를 먼저: (미국) 회사 매칭 먼저 잡고 401k/IRA/Roth, (한국) ISA / 연금저축 / IRP 같은 절세 계좌, 그 다음 일반 위탁계좌.", "자금 투입: 지금 당장 넣을 목돈이 있으면 지금 한 번에(약 2/3 확률로 유리), 월급처럼 돈이 들어오면 들어올 때마다 자동 매수(필요에 의한 분할매수 — 항상 옳음).", "두 원칙을 적는다: 절대 안 넘을 보수율 상한, 그리고 일시투자 vs 분할매수 — 그걸 수학 때문인지 마음의 평화 때문인지 정직하게.", "자동화하고 가만히: 하락장 공포 매도·작년 승자 추격 금지. 연 1회 목표 비중으로 리밸런싱. 목표 가까워지면 채권/현금 늘려 위험 축소."] },
    data: { en: ["Expense ratio (the ONLY number you must fetch): fund fact sheet, prospectus, or your broker's fund/ETF page — labeled Expense Ratio / Net Expense Ratio / TER / 총보수·보수율. Broad index funds ~0.02–0.20%; active funds often 0.5–1.5%+.", "Ticker: on the broker's fund page / quote page (e.g. VOO, VTI, 069500). Double-check — similar tickers are a classic error.", "Tracking error: fund provider fact sheet or Morningstar — how far the fund's return drifts from its index (good large-cap funds ~5 bps/yr; 1 bp = 0.01%).", "Fee-drag hand-check (no tool needed): fraction of ending balance lost to a fee over N years at ~10% growth ≈ 1 − ((1.10 − fee)/1.10)^N. At 1% fee: ~24% over 30yr, ~31% over 40yr.", "Lump-sum vs DCA evidence: Vanguard studies — lump-sum beat 3-month averaging ~2/3 of the time (MSCI World 1976–2022).", "Long-run return anchors (for expectations, not guarantees): US stocks ~10% nominal / ~7% real; Rule of 72 → money doubles every ~7yr nominal, ~10yr real."], ko: ["보수율(반드시 직접 찾아야 할 유일한 숫자): 펀드 팩트시트/투자설명서/증권사 펀드·ETF 페이지 — Expense Ratio / Net Expense Ratio / TER / 총보수·보수율 표기. 광범위 인덱스 약 0.02~0.20%, 액티브는 흔히 0.5~1.5% 이상.", "티커: 증권사 펀드/시세 페이지(예: VOO, VTI, 069500). 비슷한 티커 혼동은 흔한 실수 — 반드시 재확인.", "추적오차: 운용사 팩트시트나 모닝스타 — 펀드 수익이 지수에서 얼마나 벌어지는가(우량 대형주 펀드 약 5bp/년, 1bp=0.01%).", "수수료 손실 암산(도구 불필요): N년·연 약 10% 성장에서 수수료로 잃는 최종 잔고 비율 ≈ 1 − ((1.10 − 수수료)/1.10)^N. 1% 수수료면 30년 약 24%, 40년 약 31%.", "일시투자 vs 분할매수 근거: 뱅가드 연구 — 목돈 일시투자가 3개월 분할보다 약 2/3 확률로 우세(MSCI World 1976~2022).", "장기 수익 기준(기대치일 뿐 보장 아님): 미국 주식 명목 약 10%/실질 약 7%. 72의 법칙 → 명목 약 7년, 실질 약 10년마다 두 배."] },
    rules: { en: ["Expense ratio: broad-market fund under ~0.20% good, under ~0.10% great; 1%+ for plain market exposure is a hard no.", "A 1% fee is NOT '1% expensive' — over 30–40 years it silently eats roughly a quarter to a third of your final balance vs a near-zero fund.", "Lump-sum usually wins; DCA is fine if it stops you panic-selling — the 'cost' of that peace of mind is usually a few percent, tiny next to fees.", "'Owning the whole market' cap-weighted is NOT diversified evenly — the top 10 names ≈ a third of an S&P 500 fund.", "Judge fee relative to how well the fund tracks its index — but for plain broad-market exposure, lowest fee almost always wins.", "Account type often matters more than which fund: match > tax-advantaged wrapper > taxable."], ko: ["보수율: 광범위 펀드 약 0.20% 미만이면 양호, 0.10% 미만이면 우수. 평범한 시장 노출에 1% 이상은 무조건 거른다.", "1% 수수료는 '1% 비싼' 게 아니다 — 30~40년이면 거의 0 수수료 펀드 대비 최종 잔고의 약 4분의 1~3분의 1을 조용히 먹는다.", "보통 일시투자가 이긴다. 공황 매도를 막아준다면 분할매수도 괜찮다 — 그 대가는 대개 몇 %로, 수수료에 비하면 미미하다.", "시가총액 가중 '시장 전체 보유'는 고르게 분산된 게 아니다 — S&P500 펀드는 상위 10종목이 약 3분의 1.", "수수료는 지수 추종 품질 대비로 판단하되, 평범한 광범위 노출이면 거의 항상 최저 수수료가 이긴다.", "어떤 펀드냐보다 계좌 종류가 더 중요할 때가 많다: 회사 매칭 > 절세 계좌 > 일반 과세."] },
    pitfall: { en: "The whole strategy dies on behavior, not math: panic-selling in a crash or chasing performance destroys more wealth than any fee. And the tidy '1% = a third gone' figure is a MODEL, not a law — it depends on horizon and return; the one guaranteed truth is only that a lower fee beats a higher fee for the same fund.", ko: "이 전략의 성패는 수학이 아니라 행동에 달렸다 — 폭락장 공황 매도나 성과 추격은 어떤 수수료보다 더 큰 부를 파괴한다. 그리고 깔끔한 '1% = 3분의 1 손실' 수치는 법칙이 아니라 모델일 뿐(기간·수익률에 좌우됨). 확실한 진실은 '같은 펀드라면 낮은 수수료가 높은 수수료를 이긴다'뿐이다." },
  },
  "lifecycle": {
    id: "lifecycle",
    title: "Lifecycle / Target-Date (Glide Path + Sequence Risk)",
    what: { en: "The lowest-effort path to a long-term goal: hold one automatically-diversifying, self-de-risking fund (or a roboadvisor), and — as you near withdrawing — defend against a crash arriving early. Fits anyone saving toward retirement who does not want to manage a portfolio by hand.", ko: "장기 목표를 향한 가장 손이 덜 가는 길: 자동으로 분산되고 스스로 위험을 줄여 주는 펀드(또는 로보어드바이저) 하나를 보유하고, 인출이 가까워지면 초반 폭락에 대비하는 것. 포트폴리오를 직접 관리하고 싶지 않은 은퇴 저축자에게 적합." },
    steps: { en: ["1. Pick your equity share by HORIZON, not habit: start from 100/110/120-minus-age as a % in stocks (30s ~= 80-90%), and glide down toward ~40-50% equity near retirement.", "2. Buy ONE ready-made vehicle that runs this glide path for you: a target-date fund named for your retirement year (e.g. '2050 Fund'), or a roboadvisor set to that year. Confirm its published landing equity roughly matches your target.", "3. Check the fee before buying: read the fund's expense ratio / TER off its fact sheet or prospectus (KR: 투자설명서 / 총보수). Favor the cheapest comparable fund — a target-date fund is only as good as its fee.", "4. Automate contributions inside a tax-advantaged wrapper (KR: 연금저축 / IRP / ISA; US: 401(k) match first, then IRA/Roth), then leave it alone — the hard part is not tinkering.", "5. Near/after retirement, set a withdrawal rate (~4% of starting balance is the classic survivable anchor; higher = riskier) and hold a 2-3 year cash+bond buffer so a crash never forces you to sell stocks low.", "6. In a bad EARLY year while withdrawing, trim spending below plan if you can — it dramatically raises survival odds."], ko: ["1. 습관이 아니라 남은 기간(호라이즌)으로 주식 비중을 정한다: 주식 비중 = 100/110/120 - 나이에서 출발(30대 약 80-90%), 은퇴가 가까워지면 주식 약 40-50%까지 미끄러뜨린다.", "2. 이 글라이드 패스를 대신 굴려 주는 완성 상품 하나를 산다: 은퇴 연도가 이름에 붙은 타깃데이트 펀드(예: '2050 펀드') 또는 그 연도로 설정한 로보어드바이저. 공시된 안착 주식 비중이 내 목표와 대략 맞는지 확인.", "3. 사기 전에 보수 확인: 펀드의 총보수(TER)를 투자설명서/팩트시트에서 읽는다. 같은 조건이면 가장 싼 펀드 — 타깃데이트 펀드의 가치는 보수에 달렸다.", "4. 세제혜택 계좌 안에서 자동 납입 설정(KR: 연금저축/IRP/ISA; US: 401(k) 매칭 먼저, 그다음 IRA/Roth), 그리고 그냥 둔다 — 어려운 건 손대지 않는 것.", "5. 은퇴 직전/이후엔 인출률을 정한다(시작 잔액의 약 4%가 고전적 생존선, 높을수록 위험) 그리고 2-3년치 현금+채권 완충 자금을 둬서 폭락기에 주식을 싸게 팔지 않도록 한다.", "6. 인출 중 초반 나쁜 해엔 가능하면 계획보다 지출을 줄인다 — 생존 확률이 크게 오른다."] },
    data: { en: ["Your equity target: no source needed — compute from age (100/110/120 minus age) then adjust for pension/flexibility.", "A fund's expense ratio / TER: on the fund fact sheet or prospectus (KR: 투자설명서 / 총보수비용); provider website's fund page lists it directly.", "A target-date fund's glide path & landing equity: the provider's fund page publishes a glide-path chart and the current stock/bond mix — read the equity % at and past your target year.", "Long-run return anchors (for reasoning, not needed to buy): US stocks ~10%/yr, long bonds ~5%, cash ~3% (long-run averages; Damodaran NYU historical-returns dataset).", "Withdrawal sizing: 4% rule = ~4% of STARTING balance/yr; buffer = 2-3 years of spending in cash+bonds — both are rules of thumb, not on any filing."], ko: ["내 주식 목표 비중: 출처 불필요 — 나이(100/110/120 - 나이)로 계산 후 연금/유연성으로 조정.", "펀드 총보수(TER): 투자설명서/팩트시트, 운용사 펀드 페이지에 직접 표기.", "타깃데이트 펀드의 글라이드 패스와 안착 주식 비중: 운용사 펀드 페이지의 글라이드 패스 차트와 현재 주식/채권 비중 — 목표 연도와 그 이후의 주식 % 확인.", "장기 수익률 기준(판단용, 매수엔 불필요): 미국 주식 연 약 10%, 장기 채권 약 5%, 현금 약 3%(장기 평균; Damodaran NYU 데이터셋).", "인출 규모: 4% 법칙 = 시작 잔액의 연 약 4%; 완충 자금 = 2-3년치 생활비를 현금+채권으로 — 둘 다 경험칙, 공시자료엔 없음."] },
    rules: { en: ["Equity share should TRACK your years-to-goal: high early, glide to ~40-50% by retirement.", "While only SAVING, order of returns doesn't matter (all shares stay invested). Once WITHDRAWING, order can matter more than the average — a bad first few years is the danger.", "A simple average of yearly % overstates what compounds: -50% then +50% averages 0% but leaves you -25%.", "Withdrawal >= ~6% of start is aggressive; ~4% is the classic survivable anchor.", "Pass a target-date fund only if: fee is low AND its landing equity roughly fits your horizon.", "Red flags: paying a high expense ratio for the same glide path; picking the target year by age-you-feel instead of when you'll actually need the money; no cash buffer entering retirement."], ko: ["주식 비중은 목표까지 남은 기간을 따라가야 한다: 초반 높게, 은퇴 무렵 약 40-50%로.", "모으기만 할 땐 수익률 순서가 무의미(주식이 그대로 남음). 인출을 시작하면 순서가 평균보다 더 중요할 수 있다 — 초반 몇 해가 나쁜 게 위험.", "연간 %의 단순 평균은 복리 결과를 부풀린다: -50% 다음 +50%는 평균 0%지만 실제 -25%.", "인출률 6% 이상은 공격적; 약 4%가 고전적 생존선.", "타깃데이트 펀드 통과 조건: 보수가 낮고 AND 안착 주식 비중이 내 기간에 대략 맞을 때만.", "위험 신호: 같은 글라이드 패스인데 높은 보수를 내는 것; 실제로 돈이 필요한 시점이 아니라 기분상 나이로 목표 연도를 고르는 것; 은퇴 진입 시 현금 완충 자금이 없는 것."] },
    pitfall: { en: "The seductive trap is treating '+7.7% average return' as a promise about your ending balance. Once you are withdrawing a fixed amount, an early crash forces you to sell shares low and LOCK IN losses on a shrunken base — the same 25 real 2000-2024 returns end near ~$42k if the bad years come first vs ~$234k if they come last. Average return tells you nothing about sequence; de-risk BEFORE you start withdrawing, not after.", ko: "가장 유혹적인 함정은 '평균 +7.7% 수익률'을 최종 잔액에 대한 약속으로 여기는 것. 정액을 인출하기 시작하면 초반 폭락이 주식을 싸게 팔아 쪼그라든 기반 위에 손실을 확정하게 만든다 — 같은 2000-2024년 실제 25개 수익률이 나쁜 해가 먼저면 약 4.2만 달러, 나중이면 약 23.4만 달러로 끝난다. 평균 수익률은 순서에 대해 아무것도 말해 주지 않는다; 인출을 시작한 뒤가 아니라 시작하기 전에 위험을 줄여라." },
  },
  "diversified": {
    id: "diversified",
    title: "Diversified / All-Weather",
    what: { en: "A calm, balanced core that spreads money across stocks, bonds, real assets and cash so no single environment sinks you — for the long-run investor who wants more than an equity index but less anxiety than stock-picking.", ko: "주식·채권·실물자산·현금에 돈을 분산해 어떤 국면에서도 무너지지 않게 하는 차분한 균형 핵심 전략 — 주식 인덱스 이상을 원하되 종목 선정만큼의 불안은 원치 않는 장기 투자자용." },
    steps: { en: ["Pick ONE published mix as your target: 60/40 (60% stocks / 40% long govt bonds), All-Weather (30 stocks / 40 long bonds / 15 T-bills / 7.5 gold / 7.5 real estate), or Permanent (25% each stocks/long bonds/gold/T-bills).", "Map each sleeve to a real low-cost ETF and note its expense ratio: US stocks = VTI/VOO (KR: KODEX/TIGER S&P500 or 200), long bonds = TLT/IEF, T-bills = BIL/SHV, gold = GLD/IAU, real estate = VNQ.", "Open + fund a brokerage account (use a tax-advantaged wrapper — IRP/연금저축 in KR); buy each sleeve to its target weight with a limit order on a liquid fund.", "Fund it steadily (DCA) and rebalance on a rule: once a year, OR whenever any sleeve drifts >5% (the 5/25 band). Rebalancing forces sell-high/buy-low and stops your risk drifting.", "Sanity-check the ride you signed up for: pull your mix's annual returns (Portfolio Visualizer / fund fact sheet) and eyeball worst-year drawdown BEFORE a crash, not during one.", "Leave it alone between rebalances. The behavioral payoff — a portfolio you'll actually hold — is the whole point."], ko: ["공개된 조합 하나를 목표로 고른다: 60/40(주식 60 / 장기국채 40), 올웨더(주식 30 / 장기채 40 / 단기국채 15 / 금 7.5 / 부동산 7.5), 퍼머넌트(주식·장기채·금·단기국채 각 25%).", "각 자산을 실제 저비용 ETF에 매핑하고 보수를 확인한다: 미국주식=VTI/VOO(국내: KODEX/TIGER S&P500·200), 장기채=TLT/IEF, 단기국채=BIL/SHV, 금=GLD/IAU, 부동산=VNQ.", "증권계좌를 열고 자금을 넣는다(절세계좌 활용 — 국내는 IRP/연금저축); 유동성 좋은 종목을 지정가로 목표 비중까지 매수.", "꾸준히 납입(분할매수)하고 규칙대로 리밸런싱한다: 연 1회 또는 어떤 자산이 목표에서 5% 이상 벗어날 때(5/25 밴드). 리밸런싱이 비싸게 팔고 싸게 사게 만들고 위험이 커지는 걸 막는다.", "감수할 여정을 미리 점검한다: 내 조합의 연간 수익률을 구해(Portfolio Visualizer / 펀드 팩트시트) 폭락이 오기 전에 최악 낙폭을 눈으로 확인.", "리밸런싱 사이에는 그냥 둔다. 실제로 끝까지 들 수 있는 포트폴리오라는 행동적 보상이 전부다."] },
    data: { en: ["CAGR = (end value ÷ start value)^(1/years) − 1. Get end/start values from your broker or a return series; do the arithmetic yourself to sanity-check any tool.", "Real CAGR ≈ nominal CAGR − average inflation (CPI). The gap (usually 2–4 percentage points) is what inflation quietly ate.", "Volatility = standard deviation of the yearly return series (annualized). Typical annual vol: stocks ~15–20%, long bonds ~8–12%, gold ~15%, T-bills ~1%.", "Sharpe = (CAGR − average T-bill rate) ÷ volatility. Reward per unit of bumpiness.", "Max drawdown = the worst peak-to-trough fall = min over time of (value ÷ running peak − 1). Read it off an equity curve as the deepest dip from a prior high.", "Return series + inflation: Portfolio Visualizer or a fund fact sheet for your ETFs; CPI from your national stat office (US: FRED/Minneapolis Fed; KR: KOSIS/통계청). Long-run US asset returns: Damodaran NYU histretSP."], ko: ["CAGR = (끝값 ÷ 시작값)^(1/연수) − 1. 끝값·시작값은 증권사나 수익률 시계열에서; 직접 계산해 도구를 검산한다.", "실질 CAGR ≈ 명목 CAGR − 평균 물가상승률(CPI). 그 차이(보통 2~4%p)가 물가가 갉아먹은 몫.", "변동성 = 연간 수익률 시계열의 표준편차(연율화). 대략: 주식 15~20%, 장기채 8~12%, 금 15%, 단기국채 1%.", "샤프 = (CAGR − 평균 단기국채 수익률) ÷ 변동성. 출렁임 한 단위당 보상.", "최대 낙폭 = 최악의 고점 대비 바닥 하락 = 시간에 걸친 (값 ÷ 직전 고점 − 1)의 최솟값. 성장 곡선에서 이전 고점 대비 가장 깊은 골로 읽는다.", "수익률·물가 자료: ETF는 Portfolio Visualizer나 펀드 팩트시트, CPI는 통계기관(미국 FRED/미니애폴리스 연은, 국내 KOSIS/통계청). 장기 미국 자산 수익률: 다모다란 NYU histretSP."] },
    rules: { en: ["Judge a mix on three axes at once — return (CAGR), ride (volatility/Sharpe), worst drop (max drawdown) — never CAGR alone.", "Sharpe on long-run annual data: ~0.5 is a good realistic result; near/above 1 is rare — don't chase a textbook '>1'.", "Diversified mixes cut worst drawdown to ~12–40% vs ~37–65% for 100% stocks — but shallower, not immune.", "Rebalance to control RISK, not for a guaranteed 'bonus' — the bonus only shows up with negatively-correlated, mean-reverting assets.", "The right mix is the one whose worst drawdown you could actually hold through without selling — that number is your real risk limit."], ko: ["조합은 세 축을 동시에 본다 — 수익(CAGR), 여정(변동성/샤프), 최악의 하락(최대 낙폭) — 절대 CAGR만 보지 않는다.", "장기 연간 데이터의 샤프: 0.5 부근이면 현실적으로 좋음, 1 근처·초과는 드묾 — 교과서 '1 초과'를 좇지 말 것.", "분산 조합은 최악 낙폭을 100% 주식의 약 37~65%에서 약 12~40%로 줄인다 — 더 얕을 뿐 면역은 아니다.", "리밸런싱은 '보너스'가 아니라 위험 통제를 위해 한다 — 보너스는 음의 상관·평균회귀 자산에서만 나타난다.", "맞는 조합은 팔지 않고 버틸 수 있는 최악 낙폭을 가진 조합 — 그 숫자가 당신의 진짜 위험 한도."] },
    pitfall: { en: "Diversification is not a guarantee: in 2008 bonds rose (+~20%) while stocks crashed (−~37%) so 60/40 was cushioned, but in 2022 rising rates dropped stocks AND long bonds together (both ~−18%). When holdings fall at the SAME time, diversification barely helps — and remember drawdowns measured at year-ends understate the true within-year lows.", ko: "분산은 보장이 아니다: 2008년엔 채권이 오르고(+약 20%) 주식이 폭락(−약 37%)해 60/40이 완충됐지만, 2022년엔 금리 급등으로 주식과 장기채가 함께(둘 다 약 −18%) 떨어졌다. 자산이 같은 시점에 떨어지면 분산은 거의 도움이 안 된다 — 그리고 연말 기준 낙폭은 실제 연중 저점을 과소평가한다는 점도 기억할 것." },
  },
  "dividend-income": {
    id: "dividend-income",
    title: "Dividend Safety Check — is the payout actually reliable?",
    what: { en: "Decide rely / watch / avoid on a dividend by testing whether it is covered by earnings AND by real cash, and whether management has kept raising it — using only a filing and a calculator.", ko: "배당이 이익과 진짜 현금 모두로 감당되는지, 경영진이 계속 올려 왔는지를 따져 의지/관찰/회피를 판단합니다. 공시와 계산기만으로." },
    steps: { en: ["1. YIELD = annual dividend per share ÷ today's share price. DPS from the filing; price from any quote site. Index ~1.2% (S&P) / ~2% (KOSPI); 2.5–5% interesting, 8%+ (non-REIT) suspect.", "2. PAYOUT OF EARNINGS = total dividends paid ÷ net income (dividends in cash-flow financing section; net income = income-statement bottom line). Under ~60% safe, 60–100% thin, over 100% warning.", "3. PAYOUT OF FCF = total dividends paid ÷ FCF, FCF = operating cash flow − capex. Tougher test (cash, not profit). Over 100% = paid from savings/debt = red flag.", "4. TRACK RECORD: read DPS year-by-year. Count consecutive rising years (10+ strong / 25+ US = Aristocrat; 5–10 good in KR). Any year DPS FELL = past cut = broken promise, weigh heavily.", "5. VERDICT: reliable dividend clears all four (attractive yield + covered by earnings + covered by cash + unbroken streak). Write rely/watch/avoid + the trigger that flips it."], ko: ["1. 수익률 = 주당배당금(DPS) ÷ 오늘 주가. DPS는 공시, 주가는 시세 사이트. 지수 약 1.2%(S&P)/2%(KOSPI); 2.5~5% 관심, 8%+(리츠 아님)=의심.", "2. 순이익 대비 배당성향 = 총 지급배당금 ÷ 순이익(지급배당=현금흐름표 재무활동, 순이익=손익계산서 맨 아랫줄). 약 60% 미만 안전, 60~100% 얇음, 100% 초과 경고.", "3. FCF 대비 배당성향 = 총 지급배당금 ÷ FCF, FCF = 영업활동현금흐름 − CAPEX. 더 엄격(이익 아닌 현금). 100% 초과 = 저축/차입 지급 = 위험 신호.", "4. 이력: 연도별 DPS를 읽어 연속 증가 연수(10년+ 강함/미국 25년+=배당귀족; 한국 5~10년도 우수). DPS가 떨어진 해=과거 삭감=깨진 약속, 무겁게.", "5. 판단: 믿을 배당은 네 가지 통과(매력 수익률+이익 감당+현금 감당+깨지지 않은 이력). 의지/관찰/회피와 방아쇠를 적기."] },
    data: { en: ["Total dividends paid → cash-flow statement, FINANCING section, 'Dividends paid' / 'Cash dividends paid' (US) or 배당금의 지급 (DART).", "Operating cash flow → cash-flow statement, OPERATING section, 'Net cash provided by operating activities' / 영업활동현금흐름.", "Capex → cash-flow statement, INVESTING section, 'Purchases of PP&E' / 유형자산의 취득 (tool ignores intangibles; exclude 무형자산의 취득 to match).", "Net income → income statement, bottom line (당기순이익). DPS → dividend note, or total dividends ÷ shares outstanding.", "Price → any quote site (Yahoo/Naver). Yield is NOT on the filing — compute it: DPS ÷ price."], ko: ["총 지급배당금 → 현금흐름표 재무활동 부분, '배당금의 지급' (미국 Dividends paid).", "영업활동현금흐름 → 현금흐름표 영업활동 부분 (미국 Net cash provided by operating activities).", "CAPEX → 현금흐름표 투자활동 부분, 유형자산의 취득 (도구는 무형자산 제외 — 맞추려면 무형자산의 취득 빼기).", "순이익 → 손익계산서 맨 아랫줄(당기순이익). DPS → 배당 주석, 또는 총배당 ÷ 발행주식수.", "주가 → 시세 사이트(야후/네이버). 수익률은 공시에 없음 — DPS ÷ 주가로 계산."] },
    rules: { en: ["PASS (rely): yield ~2.5–5%, payout of earnings < ~60%, payout of FCF < 100%, 5+ yr rising DPS with no cut.", "WATCH: payout 60–100%, or FCF payout occasionally near 100%, or short/flat streak — covered but thin cushion.", "FAIL (avoid): payout of FCF > 100% (esp. two years running), OR any past DPS cut, OR 8%+ yield the coverage can't justify.", "Always read 3+ years, never one — a one-off write-down or big-capex year distorts a single year."], ko: ["합격(의지): 수익률 약 2.5~5%, 순이익 배당성향 < 약 60%, FCF 배당성향 < 100%, DPS 5년 이상 상승·삭감 없음.", "관찰: 배당성향 60~100%, 또는 FCF 배당성향 이따금 100% 근접, 또는 짧거나 평탄한 이력 — 감당되나 완충 얇음.", "탈락(회피): FCF 배당성향 > 100%(특히 2년 연속), 또는 과거 DPS 삭감, 또는 커버리지가 정당화 못 하는 8%+ 수익률.", "항상 3년 이상 보기, 한 해 금지 — 일회성 손상차손이나 대규모 설비투자 해가 한 해를 왜곡함."] },
    pitfall: { en: "A fat yield is a QUESTION, not a gift: yield rises when the PRICE falls, so 8%+ often means the market is pricing in a coming cut. Never buy for the yield before checking FCF coverage — earnings can look fine while cash can't cover the dividend (profit knocked down by non-cash depreciation, but real capex still drains cash). And the source screenshots only show landing pages — you must open the actual cash-flow statement and locate 배당금의 지급 / 영업활동현금흐름 / 유형자산의 취득 yourself.", ko: "높은 수익률은 선물이 아니라 질문: 수익률은 주가가 떨어지면 오르므로 8%+는 흔히 시장이 삭감을 미리 반영한 것. FCF 커버리지 확인 전에 수익률만 보고 사지 말 것 — 이익은 멀쩡해 보여도 현금이 배당을 못 대는 경우가 많음(비현금 감가상각이 이익을 깎지만 실제 CAPEX는 현금을 소진). 그리고 출처 스크린샷은 첫 화면만 보여줌 — 실제 현금흐름표를 열어 배당금의 지급/영업활동현금흐름/유형자산의 취득을 직접 찾아야 함." },
  },
  "value": {
    id: "value",
    title: "Value: 2-stage DCF + Margin of Safety",
    what: { en: "Estimate what a business is worth from its future cash, buy only well below that with a cushion for being wrong; for patient investors who can hold through mispricing.", ko: "기업을 미래 현금흐름으로 평가해 그 가치보다 확실히 싸게, 틀릴 것을 대비한 완충(안전마진)을 두고 산다; 저평가 해소를 기다릴 수 있는 인내심 있는 투자자에게." },
    steps: { en: ["Pull 3-5 years of FCF from the cash-flow statement: FCF = operating cash flow - CAPEX. Compute past annual growth (latest/earlier)^(1/years)-1, then haircut it (e.g. 8%->4-5%) as Stage-1 growth.", "Set discount rate = required return (8-10% ordinary, higher if risky); terminal growth small (2-3%, always below discount rate).", "2-stage DCF: grow yr1-5 FCF and discount each by 1/(1+r)^t; terminal value = yr5 FCF*(1+g)/(r-g), discounted back; sum = enterprise value; minus net debt; /shares = intrinsic value per share.", "Margin of safety = (intrinsic - price)/intrinsic. Want ~25%+; target buy price = intrinsic * 0.75.", "Check terminal-value share: if >~70% of value is terminal, it's a bet on the far future - demand more cushion.", "Cross-check Greenblatt (no forecast): earnings yield EBIT/EV (cheap?), ROC EBIT/invested capital (good?); both should agree with the DCF."], ko: ["현금흐름표에서 3~5년치 FCF: FCF = 영업활동현금흐름 - 유형자산의 취득(CAPEX). 과거 연성장률 (최근/과거)^(1/연수)-1을 구해 깎아서(예 8%->4~5%) 1단계 성장률로 쓴다.", "할인율 = 요구수익률(평범 8~10%, 위험하면 더 높게); 영구성장률은 작게(2~3%, 반드시 할인율보다 낮게).", "2단계 DCF: 1~5년 FCF를 성장시켜 각 해를 1/(1+r)^t로 할인; 잔존가치 = 5년차 FCF*(1+g)/(r-g)를 다시 할인; 합 = 기업가치; 순부채 차감; /주식수 = 주당 내재가치.", "안전마진 = (내재가치-가격)/내재가치. 약 25% 이상; 목표매수가 = 내재가치*0.75.", "잔존가치 비중 확인: 가치의 70% 이상이면 먼 미래 베팅 - 완충 더 크게.", "그린블라트 교차확인: 이익수익률 EBIT/EV(쌀까?), 자본이익률 EBIT/투하자본(좋을까?); 둘 다 DCF와 같은 방향이어야."] },
    data: { en: ["FCF = operating cash flow - CAPEX: both on the cash-flow statement (KR: 영업활동현금흐름 - 유형자산의 취득, US: PP&E purchases, shown negative).", "EBIT / operating income (영업이익): near top of the income statement.", "Total equity, total debt, cash: balance sheet - for invested capital and EV.", "Shares outstanding: balance sheet/filing cover. Price: any live quote page.", "EV = market cap (price*shares) + total debt - cash. Source: DART (dart.fss.or.kr, KR, default consolidated) / SEC EDGAR 10-K (US); US forward growth from vendors, KR none so use past FCF/EPS trend."], ko: ["FCF = 영업활동현금흐름 - CAPEX: 둘 다 현금흐름표(OCF는 영업활동, CAPEX는 투자활동의 유형자산의 취득, 음수 표시).", "EBIT/영업이익: 손익계산서 위쪽.", "자본총계·총부채·현금: 재무상태표 - 투하자본과 EV 계산에 필요.", "발행주식수: 재무상태표/보고서 표지. 주가: 실시간 시세.", "EV = 시가총액(주가*주식수) + 총부채 - 현금. 출처: DART(한국 기본 연결)/SEC EDGAR 10-K(미국); 미국 선행 성장률은 벤더, 한국은 없어 과거 FCF/EPS 추세."] },
    rules: { en: ["Margin of safety >= ~25% before acting (more for shaky businesses); negative margin = pass.", "Terminal-value share >~70% = betting on the far future - demand more cushion.", "Terminal growth must be below discount rate and <=~3%.", "Earnings yield healthy = well above the ~4-4.5% 10yr govt bond yield; ROC ~15-20%+ = likely a moat.", "If DCF says cheap but earnings yield is thin and ROC weak, the DCF leans on optimistic growth - distrust it."], ko: ["실행 전 안전마진 약 25% 이상(불안정할수록 더); 음의 마진 = 회피.", "잔존가치 비중 70% 초과 = 먼 미래 베팅 - 완충 더 크게.", "영구성장률은 할인율보다 낮고 약 3% 이하.", "이익수익률은 약 4~4.5% 국채수익률을 크게 웃돌아야 건전; 자본이익률 약 15~20%+면 해자 신호.", "DCF는 싸다는데 이익수익률 얇고 자본이익률 낮으면 DCF가 낙관적 성장률에 기댄 것 - 의심하라."] },
    pitfall: { en: "Garbage in, garbage out: a DCF outputs whatever growth you feed it, and a small terminal-growth nudge (2%->3%) can swing value ~18%. The biggest real trap is accepting the tool's optimistic default 8% growth instead of anchoring to the filing's actual FCF history and haircutting it, plus mistaking a cheap-for-a-reason value trap for a bargain.", ko: "쓰레기를 넣으면 쓰레기가 나온다: DCF는 넣은 성장률대로 뱉고, 영구성장률을 2%->3%만 올려도 가치가 약 18% 흔들린다. 최대 함정은 공시의 실제 FCF 이력에 근거해 깎지 않고 도구의 낙관적 기본값 8%를 그대로 받아들이는 것, 그리고 이유가 있어 싼 가치 함정을 헐값으로 착각하는 것." },
  },
  "growth": {
    id: "growth",
    title: "GARP — Growth at a Reasonable Price",
    what: { en: "Buy companies whose sales & profits are really growing, that fund that growth from their own cash, and only when the price per unit of growth (PEG) is sane — for investors who want growth upside without paying any price for it.", ko: "매출·이익이 실제로 성장하고, 그 성장을 자체 현금으로 감당하며, 성장 대비 가격(PEG)이 합리적일 때만 사는 전략 — 성장의 상승 여력을 원하되 아무 가격이나 치르지는 않으려는 투자자용." },
    steps: { en: ["1. REAL? Pull 4-5 years of Revenue and EPS from the income statement. Both trending up = clean growth. Revenue up but EPS flat = margin squeeze, share dilution, or a one-off — investigate. Both down = not a growth stock, stop.", "2. QUALITY/FUNDABLE? Net margin = net income ÷ revenue (judge vs peers & own trend). ROE = net income ÷ equity (want sustained 15%+). FCF conversion = (operating cash flow − CAPEX) ÷ net income (want ~80%+). SGR = ROE × (1 − payout ratio): if EPS growth >> SGR, the extra came from debt or new shares.", "3. SANE PRICE? P/E = price ÷ EPS. PEG = P/E ÷ growth%. ~1 fair, well below cheap, well above 2 = paying up. State whether your growth is forward (analyst) or past-trend — they aren't the same claim.", "4. PEER-CHECK the PEG: run 1-2 same-industry rivals; their PEG, not a fixed 1, is your yardstick (especially in Korea, where the 'Korea discount' pushes fair PEGs below 1).", "5. CALL IT: BUY / WATCH / PASS with the single biggest reason, and name the one thing that would change your mind (broken quality gate or price re-rating)."], ko: ["1. 진짜인가? 손익계산서에서 4-5년치 매출·EPS를 가져온다. 둘 다 상승 = 깔끔한 성장. 매출은 오르는데 EPS 정체 = 마진 압박·희석·일회성 — 확인. 둘 다 하락 = 성장주 아님, 중단.", "2. 우량·자체조달? 순이익률 = 당기순이익 ÷ 매출(동종업계·자사추세 대비). ROE = 당기순이익 ÷ 자기자본(꾸준히 15%+). FCF 전환율 = (영업활동현금흐름 − 유형자산의 취득) ÷ 당기순이익(약 80%+). SGR = ROE × (1 − 배당성향): EPS 성장률이 SGR을 크게 웃돌면 그 차이는 빚이나 신주에서 나온 것.", "3. 합리적 가격? PER = 주가 ÷ EPS. PEG = PER ÷ 성장률%. 1 근처 적정, 크게 아래면 저렴, 2를 크게 넘으면 비쌈. 성장률이 선행(애널리스트)인지 과거추세인지 반드시 밝힌다 — 서로 다른 주장.", "4. PEG 동종비교: 같은 업종 경쟁사 1-2곳을 돌려 그들의 PEG를 잣대로 삼는다(고정된 1이 아님). 특히 한국은 '코리아 디스카운트'로 적정 PEG가 1 아래일 수 있음.", "5. 결론: 매수/관망/보류 + 가장 큰 이유 하나, 그리고 생각을 바꿀 단 하나의 요인(우량성 관문 붕괴·가격 재평가)을 적는다."] },
    data: { en: ["Revenue, Net income, EPS → income statement (손익계산서). EPS is printed on it or = net income ÷ shares.", "Total equity → balance sheet (재무상태표), line 자본총계.", "Operating cash flow (영업활동현금흐름) & CAPEX (유형자산의 취득, under investing activities) → cash-flow statement (현금흐름표). FCF = the first minus the second.", "Dividends paid → cash-flow statement (financing) or the dividend note; payout ratio = dividends paid ÷ net income.", "Price → any live quote page. Forward EPS growth (US) → analyst consensus (e.g. broker/finance sites); Korea has no free forward feed, so use the company's own past-EPS trend.", "Sources: US = SEC EDGAR full-text search → 10-K → financial statements. KR = DART (dart.fss.or.kr) → search company → open 사업보고서 → 재무제표 → the three statements; keep basis 연결(consolidated) unless it's a holding co (홀딩스/지주 → 별도)."], ko: ["매출·당기순이익·EPS → 손익계산서. EPS는 거기 찍혀 있거나 = 순이익 ÷ 발행주식수.", "자기자본 → 재무상태표의 '자본총계' 항목.", "영업활동현금흐름 & CAPEX(유형자산의 취득, 투자활동 아래) → 현금흐름표. FCF = 앞의 것 − 뒤의 것.", "배당금 지급 → 현금흐름표(재무활동) 또는 배당 주석; 배당성향 = 배당지급액 ÷ 당기순이익.", "주가 → 아무 실시간 시세 페이지. 선행 EPS 성장률(미국) → 애널리스트 컨센서스(증권/금융 사이트); 한국은 무료 선행 데이터가 없어 자사 과거 EPS 추세를 사용.", "출처: 미국 = SEC EDGAR 전체검색 → 10-K → 재무제표. 한국 = DART(dart.fss.or.kr) → 회사 검색 → 사업보고서 → 재무제표 → 3대 재무제표; 기준은 연결 유지(지주회사 홀딩스/지주면 별도)."] },
    rules: { en: ["PEG ~1 fair; well below 1 potentially cheap; above ~2 = overpaying — but '1' is arbitrary and lower in Korea; compare to peers, not a fixed line.", "ROE sustained 15%+ = strong, single digits = weak.", "FCF conversion below ~80% = red flag that paper earnings aren't turning into cash.", "EPS growth far above SGR = growth is debt-/dilution-funded, not self-funded.", "Always label PEG's growth as forward vs past-trend; never compare the two as equal.", "Use a trend across ALL years, not a 2-point start-to-end CAGR (one freak year can double or halve the reading).", "Discard negative PEGs; PEG misfires for cyclicals, turnarounds, and dividend-heavy stalwarts."], ko: ["PEG 1 근처 적정, 1 크게 아래 저렴 가능, ~2 초과 고평가 — 단 '1'은 임의적이고 한국은 더 낮으니 고정선이 아니라 동종업체와 비교.", "ROE 15%+ 꾸준하면 강함, 한 자릿수면 약함.", "FCF 전환율 약 80% 미만 = 장부 이익이 현금이 안 되는 경고.", "EPS 성장률이 SGR을 크게 웃돌면 = 자체가 아니라 빚·희석으로 만든 성장.", "PEG의 성장률이 선행인지 과거추세인지 반드시 표기; 둘을 같은 것으로 비교 금지.", "처음-끝 2점 CAGR가 아니라 모든 해를 쓰는 추세로 판단(이상한 한 해가 값을 두 배·절반으로 왜곡).", "음(-) PEG는 버린다; PEG는 경기순환주·턴어라운드·고배당 대형주에서는 오작동."] },
    pitfall: { en: "The whole PEG hangs on the growth denominator, which is a forecast (or, in Korea, a past-trend extrapolation) that's routinely too optimistic — a 'cheap' PEG and a value trap look identical on screen. Sanity-check the growth number against actual reported history, demand real cash behind the earnings (FCF conversion), and never let 'invest in what you know' skip the homework: a good company at a high PEG is still a bad stock.", ko: "PEG 전체가 분모의 성장률에 달려 있는데, 이는 대개 지나치게 낙관적인 전망치(한국은 과거추세 외삽)여서 '싼' PEG와 가치함정이 화면상 똑같아 보인다. 성장률을 실제 보고된 실적과 대조하고, 이익 뒤에 진짜 현금(FCF 전환율)을 요구하며, '아는 것에 투자하라'가 숙제를 건너뛰는 핑계가 되지 않게 하라 — 높은 PEG의 좋은 기업도 나쁜 주식이다." },
  },
  "factor-quant": {
    id: "factor-quant",
    title: "Factor / Quant: X-ray a factor ETF",
    what: { en: "Buy proven return drivers (value/size/momentum/quality/low-vol) cheaply via long-only factor ETFs, and verify each fund delivers the tilt it advertises by regressing its returns on the Fama-French factors - for the rules-based investor who wants exposure, not a stock-picker.", ko: "검증된 수익 동인(가치·규모·모멘텀·퀄리티·저변동성)을 저비용 롱온리 팩터 ETF로 사되, 각 펀드가 광고하는 성향을 실제로 주는지 파마-프렌치 팩터 회귀로 검증한다 - 종목선정가가 아닌 '노출'을 원하는 규칙 기반 투자자용." },
    steps: { en: ["Pick a factor ETF whose tilt you can predict (e.g. VTV=value, VLUE=deep value, USMV=low-vol, MTUM=momentum).", "Get its monthly returns: Yahoo Finance > Historical Data > monthly > use the Adj Close column; return_t = AdjClose_t / AdjClose_(t-1) - 1.", "Download 'Fama/French 3 Factors' (monthly) from the Ken French Data Library; columns are Mkt-RF, SMB, HML, and a separate RF.", "Compute YOUR excess return each month = fund return - RF. Regress it on Mkt-RF, SMB, HML (spreadsheet: LINEST / Data Analysis > Regression, Y = excess return, X = the 3 factor columns).", "Read the output: slopes = betas (Mkt/SMB/HML loadings), intercept = monthly alpha (x12 approx annual), R-squared = fraction of wiggle explained.", "Confirm the tilt is real, check for unwanted loadings, compare alpha to the fund's fee, then keep-or-skip."], ko: ["성향을 예측할 수 있는 팩터 ETF를 고른다(예: VTV=가치, VLUE=딥밸류, USMV=저변동성, MTUM=모멘텀).", "월별 수익률 확보: 야후 파이낸스 > Historical Data > 월간 > Adj Close(수정종가) 열 사용; 수익률_t = 수정종가_t / 수정종가_(t-1) - 1.", "케네스 프렌치 데이터 라이브러리에서 'Fama/French 3 Factors'(월간) 다운로드; 열은 Mkt-RF, SMB, HML, 그리고 별도 RF.", "매달 내 초과수익 = 펀드수익 - RF. 이것을 Mkt-RF·SMB·HML에 회귀(스프레드시트: LINEST / 데이터분석 > 회귀분석, Y=초과수익, X=팩터 3열).", "결과 읽기: 기울기 = 베타(Mkt/SMB/HML 로딩), 절편 = 월 알파(x12 연 알파 근사), R-제곱 = 설명된 등락 비중.", "성향이 진짜인지 확인, 원치 않은 로딩 점검, 알파를 수수료와 비교, 채택/제외 결정."] },
    data: { en: ["Fund monthly returns: Yahoo Finance > ticker > Historical Data > frequency Monthly > ADJ CLOSE column (split/dividend-adjusted); turn into returns yourself.", "Factor return series (Mkt-RF, SMB, HML, RF): Kenneth R. French Data Library (Tuck/Dartmouth), 'Fama/French 3 Factors' CSV/ZIP, monthly.", "Expense ratio (annual % fee): issuer product page - Vanguard for VTV (~0.04%), iShares/BlackRock for MTUM/QUAL/USMV/VLUE (~0.15%) - or the fund's Yahoo profile.", "Alpha, betas, R-squared: the intercept, slopes, and fit-score from a linear regression of your excess return on the 3 factor columns (spreadsheet LINEST/Regression)."], ko: ["펀드 월별 수익률: 야후 파이낸스 > 티커 > Historical Data > 월간 > ADJ CLOSE 열(분할·배당 반영); 직접 수익률로 변환.", "팩터 시계열(Mkt-RF, SMB, HML, RF): 케네스 프렌치 데이터 라이브러리(다트머스), 'Fama/French 3 Factors' CSV/ZIP, 월간.", "총보수(연 % 수수료): 발행사 상품 페이지 - VTV는 뱅가드(약 0.04%), MTUM/QUAL/USMV/VLUE는 iShares(약 0.15%) - 또는 펀드 야후 프로필.", "알파·베타·R-제곱: 초과수익을 팩터 3열에 회귀한 절편·기울기·적합도(스프레드시트 LINEST/회귀분석)."] },
    rules: { en: ["Tilt is real only if the claimed factor's beta is clearly positive (~+0.3 or more); +0.05 = 'value in name only'; a negative HML on a 'value' fund = red flag.", "Mkt beta should sit near 1 (USMV deliberately below 1). Watch for unwanted loadings (a 'value' fund also heavy on SMB = a size bet you didn't order).", "Alpha near-zero or slightly negative by ~the expense ratio = GOOD (pure factor beta). A big positive alpha over a short window = suspicion, not skill.", "High R-squared (~0.9+) for value/market funds = factors explain it. Lower R-squared for momentum/quality funds is expected - the 3-factor model has no momentum/quality factor, so the missing loading IS the finding.", "24 months minimum history; betas drift - treat as a snapshot, not a guarantee.", "CSV gotchas: values are percent-per-period (2.0 = 2%), factors are already excess (subtract RF from YOUR return too), and -99.99 = missing (filter out)."], ko: ["성향이 진짜이려면 주장한 팩터의 베타가 뚜렷하게 플러스(약 +0.3 이상). +0.05 = '이름만 가치'; '가치' 펀드의 음(-) HML = 위험신호.", "Mkt 베타는 1 근처(USMV는 의도적으로 1 미만). 원치 않은 로딩 주의('가치' 펀드가 SMB에도 크면 청하지 않은 규모 베팅).", "알파가 0 근처거나 총보수만큼 살짝 마이너스 = 좋음(순수 팩터 베타). 짧은 기간의 큰 플러스 알파 = 실력 아니라 의심 대상.", "가치·시장 펀드는 R-제곱 높음(약 0.9+) = 팩터가 설명. 모멘텀·퀄리티 펀드는 R-제곱 낮은 게 정상 - 3팩터엔 모멘텀·퀄리티가 없어 로딩의 '부재'가 곧 발견.", "최소 24개월 이력; 베타는 흐른다 - 보증이 아니라 스냅샷으로.", "CSV 함정: 값은 기간당 퍼센트(2.0 = 2%), 팩터는 이미 초과수익(내 수익에서도 RF를 빼라), -99.99 = 결측(제거)."] },
    pitfall: { en: "You'll gather every input but can stall at the actual regression - no source here shows how to run 3-variable OLS in a spreadsheet (Excel LINEST or Data Analysis > Regression: Y = your monthly excess return, X = the Mkt-RF/SMB/HML columns). And remember the deeper trap the path stresses: a long-only ETF captures only PART of the academic long/short premium, factor droughts run a decade (value 2007-2020), and chasing last year's hot factor or bailing mid-drought turns a modest real edge into a loss.", ko: "입력은 다 모아도 정작 회귀에서 막힐 수 있다 - 스프레드시트에서 3변수 OLS를 돌리는 법(엑셀 LINEST 또는 데이터분석 > 회귀분석: Y=내 월별 초과수익, X=Mkt-RF/SMB/HML 열)을 어디서도 보여주지 않는다. 더 깊은 함정도 기억하라: 롱온리 ETF는 학술적 롱숏 프리미엄의 일부만 잡고, 팩터 침체는 10년씩 간다(가치 2007-2020). 작년의 뜨거운 팩터를 좇거나 침체 중간에 팔면 작은 진짜 우위가 손실로 바뀐다." },
  },
  "global-macro": {
    id: "global-macro",
    title: "Global Macro — Regime Reading",
    what: { en: "Read the growth/inflation regime from a few official macro signals and tilt (not lurch) your allocation toward what that environment tends to favor — for the investor who wants to position around the big picture, humbly and probabilistically.", ko: "몇 개의 공식 매크로 신호로 성장/인플레이션 국면을 읽고, 그 환경이 유리하게 보는 쪽으로 자산배분을 (급전환이 아니라) 살짝 기울이는 전략 — 큰 그림에 확률적·겸손하게 포지션하려는 투자자를 위한 것." },
    steps: { en: ["1) Pull the 10yr-3mo Treasury spread on FRED (series T10Y3M). Below 0 = inverted = historical recession WARNING (not a timer; the 2022-24 inversion gave no recession).", "2) Get inflation: FRED CPIAUCSL, compute YoY = this month's index / same month last year - 1. Note the LEVEL (~2% target) and the DIRECTION (rising/falling vs ~6mo ago).", "3) Check Sahm: 3-month-avg unemployment (FRED UNRATE) minus its lowest 3-mo-avg in the trailing 12 months; >= +0.50pp = recession likely already starting. (Shortcut: FRED publishes the finished series SAHMCURRENT.)", "4) Place yourself in the growth x inflation quadrant (growth up/down x inflation up/down): Goldilocks / Reflation / Stagflation / Deflation.", "5) Combine all four - do they agree or conflict? State one regime read and ONE small allocation tilt it implies, plus what would flip it.", "6) Express the view as a small sized tilt in your actual account - never leverage."], ko: ["1) FRED에서 10년-3개월 국채 금리차(시계열 T10Y3M)를 본다. 0 아래 = 역전 = 역사적 침체 경고(타이머 아님; 2022~24 역전은 침체로 이어지지 않음).", "2) 인플레이션: FRED CPIAUCSL로 YoY = 이번 달 지수 / 작년 같은 달 지수 - 1 계산. 수준(~2% 목표)과 방향(약 6개월 전 대비 상승/하락)을 함께 본다.", "3) 삼(Sahm) 확인: 실업률(FRED UNRATE)의 3개월 평균 - 지난 12개월 중 그 3개월 평균 최저점; >= +0.50%p면 침체가 이미 시작 중일 가능성. (지름길: FRED가 완성 시계열 SAHMCURRENT를 발표함.)", "4) 성장 x 인플레이션 사분면에 자신을 위치시킨다(성장 상/하 x 인플레 상/하): 골디락스 / 리플레이션 / 스태그플레이션 / 디플레이션.", "5) 네 신호를 결합 - 일치하는가 충돌하는가? 하나의 국면 판독과 그것이 함의하는 작은 자산배분 기울기 하나, 그리고 무엇이 뒤집을지를 적는다.", "6) 그 관점을 실제 계좌에서 작게 조절된 기울기로 표현 - 레버리지는 절대 금물."] },
    data: { en: ["Yield-curve spread: FRED series T10Y3M (10yr-3mo, in percentage points). Read against zero. Or subtract by hand: DGS10 - DGS3MO.", "Inflation YoY: FRED CPIAUCSL (a unitless index ~310-334, base=100). YoY = index_now / index_12mo_ago - 1. The division is what turns the index into 'inflation %'.", "Sahm: FRED UNRATE (unemployment %). 3-mo avg now minus lowest 3-mo avg over trailing 12mo, in pp. Or read FRED's ready series SAHMCURRENT directly.", "Quadrant growth axis: falling unemployment over ~6mo = growth rising (the lab's proxy). Canonical version = growth & inflation vs. market EXPECTATIONS (Dalio/All-Weather).", "All series are US, keyless, on fred.stlouisfed.org - search the code, click 'Max' for full history. Numbers get REVISED weeks/months later."], ko: ["장단기 금리차: FRED 시계열 T10Y3M(10년-3개월, %포인트). 0 기준으로 읽기. 손으로는 DGS10 - DGS3MO.", "인플레이션 YoY: FRED CPIAUCSL(단위 없는 지수 ~310~334, 기준=100). YoY = 현재 지수 / 12개월 전 지수 - 1. 이 나눗셈이 지수를 '인플레이션 %'로 바꾼다.", "삼(Sahm): FRED UNRATE(실업률 %). 지금 3개월 평균 - 지난 12개월 최저 3개월 평균, 단위 %p. 또는 FRED 완성 시계열 SAHMCURRENT를 바로 읽기.", "사분면 성장축: 약 6개월간 실업률 하락 = 성장 상승(랩의 근사치). 정통 버전 = 성장·인플레이션을 시장 예상과 비교(달리오/올웨더).", "모든 시계열은 미국·키 불필요, fred.stlouisfed.org에서 코드 검색 후 'Max'로 전체 이력. 숫자는 수 주~수 개월 뒤 수정됨."] },
    rules: { en: ["Spread < 0 (inverted) = recession risk elevated - a warning light, lag has run months to >1 year.", "Inflation: ~2% = target, ~3-4% = warm, high single digits = hot; direction matters as much as level.", "Sahm >= +0.50pp = labor market deteriorating fast, recession likely already begun.", "Quadrant tilts (tendencies, not laws): Goldilocks->stocks; Reflation->stocks+commodities; Stagflation->commodities+inflation-linked bonds(TIPS); Deflation->long govt bonds+cash.", "NEVER trade a single indicator; combine all four and act on the balance. Output a tilt, not an all-in bet."], ko: ["금리차 < 0(역전) = 침체 위험 상승 - 경고등이며 시차는 수개월~1년 이상.", "인플레이션: ~2%=목표, ~3~4%=다소 높음, 높은 한 자릿수=과열; 수준만큼 방향이 중요.", "삼 >= +0.50%p = 노동시장 급속 악화, 침체가 이미 시작됐을 가능성.", "사분면 기울기(경향, 법칙 아님): 골디락스->주식; 리플레이션->주식+원자재; 스태그플레이션->원자재+물가연동채(TIPS); 디플레이션->장기국채+현금.", "단일 지표로 절대 매매 금지; 네 신호를 결합해 균형에 따라 행동. 몰빵이 아니라 기울기를 내라."] },
    pitfall: { en: "These signals lag, whipsaw, and rest on numbers that get revised - the 'never wrong' yield curve inverted for 2+ years (2022-24) with NO recession. A regime read is a probabilistic hypothesis to position around, never a market-timing trigger; the moment you turn one flashing indicator into an all-in, leveraged bet is the moment it wrecks you.", ko: "이 신호들은 지연되고, 톱니처럼 번갈아 속이며, 나중에 수정되는 숫자에 기댄다 - '틀린 적 없다'는 수익률 곡선이 2년 넘게(2022~24) 역전됐는데도 침체는 없었다. 국면 판독은 포지션의 근거가 될 확률적 가설일 뿐 마켓타이밍 트리거가 아니다; 하나의 깜빡이는 지표를 몰빵·레버리지 베팅으로 바꾸는 순간이 파산의 순간이다." },
  },
  "trend-momentum": {
    id: "trend-momentum",
    title: "Trend Following / Momentum",
    what: { en: "Own an asset only while it's trending up by a fixed mechanical rule and step aside when it turns down — for the disciplined rule-follower who values smaller drawdowns over max return and can sit through whipsaws without overriding the rule.", ko: "고정된 기계적 규칙으로 자산이 상승 추세일 때만 보유하고 하락 전환 시 물러난다 — 최대 수익보다 더 작은 낙폭을 중시하고, 휩쏘를 규칙을 어기지 않고 견딜 수 있는 규율형 투자자에게." },
    steps: { en: ["1. Get the data: pull years of DAILY split/dividend-ADJUSTED closes (US: Yahoo Finance → Historical Data → 'Adj Close' column; KR: Naver 금융/KRX 수정주가). You need High & Low too for Donchian. Window must contain at least one real -20% bear.", "2. Pick ONE rule and compute it by hand each day. 200d-MA: average the last 200 adjusted closes; long if today's close > that average, else cash. 12-1 momentum: compare today's price to the price ~12 months (252 trading days) ago but skip the last ~21 days; long if higher. Donchian-50: long when today's close > the highest close of the prior 50 days; exit when close < the lowest low of the prior 50.", "3. Decide TODAY's position from data up to today, then earn tomorrow's move — never use tomorrow's price to decide today (that's look-ahead, and it fakes any backtest).", "4. Score it vs buy-and-hold: max drawdown = (peak − trough)/peak on the equity curve; CAGR = (ending/starting)^(1/years) − 1. Read DRAWDOWN first, then return.", "5. Judge risk-adjusted: return-per-drawdown = CAGR ÷ drawdown size. Use the system only if it clearly cuts drawdown, gives up acceptable return, AND you'd truly follow it through the whipsaws."], ko: ["1. 데이터 확보: 수년치 일간 분할·배당 수정 종가를 받는다(미국: 야후 파이낸스 → Historical Data → 'Adj Close' 열; 한국: 네이버 금융/KRX 수정주가). 돈치안은 고가·저가도 필요. 구간에 실제 -20% 약세장이 최소 한 번 있어야 한다.", "2. 규칙 하나를 골라 매일 손으로 계산. 200일선: 최근 200 수정종가 평균 → 오늘 종가가 그 위면 진입, 아니면 현금. 12-1 모멘텀: 오늘 가격과 약 12개월(252거래일) 전 가격 비교하되 최근 약 21일은 건너뜀 → 더 높으면 진입. 돈치안-50: 오늘 종가 > 직전 50일 최고 종가면 진입, 종가 < 직전 50일 최저 저가면 청산.", "3. 오늘 포지션은 오늘까지의 데이터로 정하고, 내일 움직임을 취한다 — 내일 가격으로 오늘을 정하지 마라(룩어헤드, 어떤 백테스트든 가짜로 좋아 보이게 함).", "4. 매수후보유와 비교 채점: 최대낙폭 = (고점 − 저점)/고점; CAGR = (종료/시작)^(1/연수) − 1. 수익률보다 낙폭을 먼저 읽어라.", "5. 위험조정 판단: 낙폭 대비 수익 = CAGR ÷ 낙폭 크기. 낙폭을 확실히 줄이고, 포기 수익이 받아들일 만하며, 휩쏘를 뚫고 실제로 따를 수 있을 때만 시스템을 쓴다."] },
    data: { en: ["Daily ADJUSTED close — Yahoo Finance 'Historical Data' → 'Adj Close' column (adjusted for BOTH splits and dividends; plain 'Close' fixes splits only). KR: Naver 금융 시세 / KRX 수정주가.", "Daily High & Low — same Yahoo history table (O/H/L/C/V columns); needed for Donchian breakouts and for ATR.", "200-day SMA = sum of the last 200 adjusted closes ÷ 200 (recompute each day, dropping the oldest, adding the newest).", "12-1 momentum = (price 21 trading days ago ÷ price 252 trading days ago) − 1; positive = uptrend.", "Max drawdown = (running peak of your equity − later trough) ÷ that peak; CAGR = (end value ÷ start value)^(1/years) − 1, years ≈ trading days ÷ 252.", "ATR (for sizing/stops) = average of the last 14 True Ranges, where TR = max(High−Low, |High−PrevClose|, |Low−PrevClose|)."], ko: ["일간 수정 종가 — 야후 파이낸스 'Historical Data' → 'Adj Close' 열(분할·배당 모두 반영; 일반 'Close'는 분할만). 한국: 네이버 금융 시세 / KRX 수정주가.", "일간 고가·저가 — 같은 야후 과거 시세 표(O/H/L/C/V 열); 돈치안 돌파와 ATR에 필요.", "200일 SMA = 최근 200 수정종가 합 ÷ 200(매일 재계산, 가장 오래된 것 빼고 새것 더함).", "12-1 모멘텀 = (21거래일 전 가격 ÷ 252거래일 전 가격) − 1; 양(+)이면 상승 추세.", "최대낙폭 = (자산곡선의 진행 고점 − 이후 저점) ÷ 그 고점; CAGR = (종료값 ÷ 시작값)^(1/연수) − 1, 연수 ≈ 거래일수 ÷ 252.", "ATR(사이징·손절용) = 최근 14개 True Range 평균, TR = max(고−저, |고−전일종가|, |저−전일종가|)."] },
    rules: { en: ["Judge DRAWDOWN before return: system drawdown clearly shallower than buy-and-hold (e.g. -20% vs -50%) = the rule earned its keep; roughly equal = it's just adding trades/costs.", "Return-per-drawdown = CAGR ÷ drawdown; higher wins. 8%/-20% (=0.4) beats 10%/-50% (=0.2) even though it earned less.", "Trend systems USUALLY trail buy-and-hold on raw CAGR — that's normal (cash time + whipsaw losses); the trade you're buying is less pain, not more return.", "Only trade in a trending regime: ADX > ~25 = follow; ADX < ~20 = range, trend rules get chopped up. A drawdown cut of only a few points (-45% vs -50%) is NOT worth the trades."], ko: ["수익률보다 낙폭 먼저: 시스템 낙폭이 매수후보유보다 확실히 얕으면(예: -20% 대 -50%) 규칙이 값을 함; 비슷하면 매매·비용만 늘린 것.", "낙폭 대비 수익 = CAGR ÷ 낙폭; 높을수록 승. 8%/-20%(=0.4)는 덜 벌어도 10%/-50%(=0.2)를 이긴다.", "추세 시스템은 원시 CAGR에서 대개 매수후보유에 뒤진다 — 정상(현금 보유 + 휩쏘 손실); 사는 것은 더 큰 수익이 아니라 더 적은 고통이다.", "추세 국면에서만 매매: ADX > 약 25면 추종, ADX < 약 20이면 횡보라 추세 규칙이 갈린다. 낙폭이 몇 포인트만 줄면(-45% 대 -50%) 거래할 값어치가 없다."] },
    pitfall: { en: "The backtest hides the real killer: WHIPSAWS in choppy markets and your own discretion. It ignores the bid-ask spread, slippage and taxes (every round trip quietly loses the spread and can trigger a taxable gain), and it's ONE symbol over ONE history — no promise about the future. A great rule you abandon at the bottom of a deep drawdown is worse than buy-and-hold you never touch, so be brutally honest that you'd actually follow it.", ko: "백테스트는 진짜 킬러를 숨긴다: 횡보장의 휩쏘와 당신의 재량. 매수·매도 스프레드·슬리피지·세금을 무시하고(왕복마다 스프레드를 잃고 과세 이익이 생길 수 있음), 한 종목의 한 역사일 뿐 — 미래 보장이 아니다. 깊은 낙폭 바닥에서 버릴 훌륭한 규칙은 절대 손대지 않을 매수후보유보다 나쁘니, 정말 따를 수 있을지 냉정하게 정직하라." },
  },
  "event-driven": {
    id: "event-driven",
    title: "Merger Arb (Event-Driven)",
    what: { en: "Buy an announced all-cash takeover target below the offer price to collect the small spread when the deal closes — accepting a rare large loss if it breaks; fits patient investors who can read a filing and judge deal risk, not day-traders.", ko: "발표된 전액현금 인수 대상 주식을 인수가보다 싸게 사서 딜 성사 시 작은 스프레드를 거두는 전략 — 드물게 딜이 깨지면 큰 손실을 감수. 공시를 읽고 딜 위험을 판단할 수 있는 인내심 있는 투자자에게 맞고, 단타용이 아님." },
    steps: { en: ["Confirm the deal is ALL-CASH with a fixed offer price (stock/mixed deals need an exchange-ratio hedge — skip until you know it).", "Pull the offer price + expected close date from the 8-K / DEFM14A / press release; pull current price from any quote; pull the pre-announcement (break) price from a chart = the close the trading day BEFORE the announcement.", "Spread% = (offer − current) ÷ current. Annualize: spread% × (365 ÷ days-to-close).", "Downside% = (current − break price) ÷ current. Clean-closes-per-break = downside% ÷ spread%.", "Implied P(close) = (current − break) ÷ (offer − break). Ask if YOU think the true odds are higher/lower, citing regulatory, financing, or vote risk.", "Take it only if the pay compensates the asymmetry AND you have a view on at least one break risk."], ko: ["딜이 고정 인수가의 전액현금인지 확인 (주식/혼합 딜은 교환비율 헤지가 필요 — 익히기 전엔 건너뜀).", "인수가·예상 종료일은 8-K/DEFM14A/보도자료에서, 현재가는 시세창에서, 발표 전(결렬) 가격은 차트에서 = 발표 '하루 전' 거래일 종가.", "스프레드% = (인수가 − 현재가) ÷ 현재가. 연율화: 스프레드% × (365 ÷ 종료일수).", "하방% = (현재가 − 결렬가) ÷ 현재가. 결렬당 정상종료 횟수 = 하방% ÷ 스프레드%.", "암시 P(종료) = (현재가 − 결렬가) ÷ (인수가 − 결렬가). 규제·자금조달·주주표결 위험을 근거로 실제 확률이 더 높은지/낮은지 판단.", "대가가 비대칭을 보상하고, 최소 한 가지 결렬 위험에 견해가 있을 때만 진입."] },
    data: { en: ["Offer price + close date: SEC EDGAR merger 8-K (filed within ~4 business days) and the DEFM14A proxy — look for '$X.XX per share in cash' in the opening recitals; cross-check the press release. NOT in the 10-K.", "Current price: any quote page (Yahoo/Google Finance/broker).", "Pre-announcement / break price: a price CHART — find the announcement date, read the closing price of the trading day before it. This number is in NO filing.", "Break-risk signals (regulator overlap, committed financing letter, break fee, board backing, premium size): the 8-K / proxy / press release."], ko: ["인수가·종료일: SEC EDGAR의 합병 8-K(사건 후 영업일 약 4일 내)와 DEFM14A 위임장 — 맨 앞 낭독조항의 '주당 $X.XX 현금' 문구; 보도자료와 교차확인. 10-K에는 없음.", "현재가: 아무 시세창(Yahoo/Google Finance/증권사).", "발표 전/결렬 가격: 주가 차트 — 발표일을 찾아 '하루 전' 거래일 종가를 읽음. 어떤 공시에도 없음.", "결렬 위험 신호(사업 겹침, 확약 자금조달서, 위약금, 이사회 지지, 프리미엄 크기): 8-K/위임장/보도자료."] },
    rules: { en: ["Annualized spread is a RANKING tool, not a promise — it assumes you instantly reinvest and that the timeline holds; a delay collapses it.", "The number that keeps you honest = downside% ÷ spread% (how many clean closes one break wipes out) — often ~10-13x. Respect the asymmetry.", "A WIDER spread means the market is more nervous, not a free lunch.", "No view on regulatory / financing / vote risk = no edge; pass.", "Market-neutral until it isn't: in crashes deals break in clusters and beta spikes."], ko: ["연율화 스프레드는 약속이 아니라 순위 도구 — 즉시 재투자와 일정 준수를 가정; 지연되면 무너짐.", "정직하게 붙잡는 숫자 = 하방% ÷ 스프레드%(한 번의 결렬이 지우는 정상종료 횟수) — 흔히 약 10~13배. 비대칭을 존중.", "넓은 스프레드는 공짜 점심이 아니라 시장의 불안 신호.", "규제·자금조달·표결 위험에 견해가 없으면 우위 없음 → 넘김.", "평소 시장중립이지만 폭락 시 딜이 무더기로 깨지고 베타 급등."] },
    pitfall: { en: "The break price is a GUESS, not an observed fact — the bad news that kills a deal can push the stock even below its pre-announcement level, so your computed downside and implied odds are only as honest as that anchor; never treat the implied probability as measured certainty.", ko: "결렬 가격은 사실이 아니라 추정치 — 딜을 깬 악재가 주가를 발표 전 수준보다 더 아래로 밀 수 있어, 계산한 하방과 암시 확률은 그 기준점만큼만 정직함; 암시 확률을 측정된 확실성으로 착각하지 말 것." },
  },
  "real-assets": {
    id: "real-assets",
    title: "REIT Income Check (FFO/AFFO coverage)",
    what: { en: "Judge whether a REIT's fat distribution is actually covered by cash — using FFO/AFFO, not the net-income payout that lies for REITs. Fits income investors who want reliable real-estate yield.", ko: "리츠의 두둑한 분배금이 실제로 현금으로 감당되는지, 리츠에서 거짓말하는 순이익 배당성향이 아니라 FFO/AFFO로 판단하기. 안정적인 부동산 인컴을 원하는 인컴 투자자에게 적합." },
    steps: { en: ["Ignore the net-income payout ratio — for a REIT, depreciation (a huge non-cash charge) crushes net income, so a payout 'over 100%' is normal, not a warning.", "Open the latest filing and search text for 'FFO' / 'Funds from operations': earnings release or quarterly supplemental first (fastest; often an 8-K exhibit on EDGAR), else the 10-Q/10-K.", "In the 'Reconciliation of net income to FFO' table: Net income + depreciation & amortization ± property-sale gains(−)/losses(+) = FFO; then − recurring/maintenance capex = AFFO.", "Get the numerator = total distributions PAID (not per-share, not 'declared'): cash-flow statement, financing section, or DPS × shares outstanding. Match the same period as FFO.", "Compute AFFO payout = distributions ÷ AFFO. Cross-check yield vs same-property-type peers and eyeball the DPS-by-year chart for past cuts.", "Write your call: rely / watch / avoid, quoting the AFFO payout + the exact source line, and what would flip it (e.g. AFFO payout crossing 100%)."], ko: ["순이익 배당성향은 무시 — 리츠는 감가상각(거대한 비현금 비용)이 순이익을 짓눌러 '100% 초과'가 정상이지 경고가 아님.", "최신 공시를 열어 'FFO'/'Funds from operations' 검색: 실적 발표자료·분기 보충자료 먼저(가장 빠름; EDGAR에선 흔히 8-K 첨부), 없으면 10-Q/10-K.", "'순이익→FFO 조정표'에서: 순이익 + 감가상각 및 무형자산상각 ± 부동산 매각이익(−)/손실(+) = FFO; 그다음 − 경상(유지)자본지출 = AFFO.", "분자 = 총 지급 분배금(주당 아님, '선언'분 아님): 현금흐름표 재무활동 구간, 또는 DPS × 발행주식수. FFO와 같은 기간으로 맞춤.", "AFFO 배당성향 = 분배금 ÷ AFFO 계산. 같은 부동산 유형 동종그룹과 수익률 비교, 연도별 DPS 차트로 과거 삭감 확인.", "판정 기록: 의지/관찰/회피, AFFO 배당성향 + 정확한 출처 줄 인용, 무엇이 판단을 뒤집는지(예: AFFO 배당성향 100% 돌파)."] },
    data: { en: ["Net income + Depreciation & amortization: income statement (D&A also on cash-flow statement top).", "FFO / AFFO reconciliation: earnings release or quarterly supplemental (usually an 8-K exhibit on EDGAR), or the 10-Q/10-K — search text for 'FFO'. Non-GAAP, so it is NOT in machine-readable XBRL; you read it by hand.", "Distributions PAID (numerator): cash-flow statement, financing section, 'distributions/dividends paid' — or DPS × shares outstanding.", "Yield = annual distribution ÷ share price: any quote page (DPS $3 on $50 → 6%).", "Korea: DART (opendart.fss.or.kr) 사업보고서 → financial-statement notes → 배당가능이익 (distributable income) as the legal coverage denominator; distribution schedule for actual paid."], ko: ["순이익 + 감가상각 및 무형자산상각: 손익계산서(감가상각은 현금흐름표 상단에도).", "FFO/AFFO 조정표: 실적 발표자료·분기 보충자료(EDGAR에선 대개 8-K 첨부) 또는 10-Q/10-K — 'FFO' 텍스트 검색. 비GAAP이라 기계판독 XBRL에 없음; 직접 읽음.", "지급 분배금(분자): 현금흐름표 재무활동 구간 '배당금 지급' — 또는 DPS × 발행주식수.", "수익률 = 연간 분배금 ÷ 주가: 아무 시세 페이지(주가 50달러에 DPS 3달러 → 6%).", "한국: DART(opendart.fss.or.kr) 사업보고서 → 재무제표 주석 → 배당가능이익을 법적 커버리지 분모로; 실제 지급액은 배당 내역에서."] },
    rules: { en: ["AFFO payout < ~90% = covered; 90–100% = borderline (thin cushion); > 100% = real warning (paying out more cash than it earns).", "FFO payout under 100% is encouraging context, but AFFO decides — it already subtracts maintenance capex.", "Yield ~3–6% is normal for equity REITs; 10%+ is a flag (market pricing in a cut), not a bargain.", "Compare yield only against same-property-type REITs (apartments vs warehouses vs malls); cross-type is apples-to-oranges.", "A distribution that never got cut through a downturn beats a high headline yield."], ko: ["AFFO 배당성향 90% 미만 = 감당됨; 90~100% = 경계(여유 얇음); 100% 초과 = 진짜 경고(버는 현금보다 많이 배당).", "FFO 배당성향 100% 미만은 안심 참고치이나, 판정은 AFFO — 유지자본지출까지 이미 뺐음.", "지분형 리츠 수익률 3~6%가 정상; 10% 이상은 경고(삭감 선반영)이지 저평가 아님.", "수익률은 같은 부동산 유형 리츠끼리만 비교(아파트 vs 물류창고 vs 쇼핑몰); 유형 다르면 사과-오렌지.", "불황을 지나면서도 삭감 없던 분배 이력이 높은 표면 수익률보다 낫다."] },
    pitfall: { en: "The killer move is judging a REIT on the net-income payout (over 100% looks like a cut is coming — it isn't; depreciation is a paper charge). But the two hard real-world steps are FINDING the FFO reconciliation table in the filing (non-GAAP, not in structured data, buried in a supplemental/8-K exhibit or deep in the 10-K) and grabbing the RIGHT recurring-capex line for AFFO — capex is often unlabeled or inconsistent and AFFO has no standard formula, so a wrong line quietly distorts your coverage number. Rate sensitivity is the macro trap: 'inflation hedge' REITs can still fall hard when rates spike (2022).", ko: "치명적 실수는 리츠를 순이익 배당성향으로 판단하는 것(100% 초과가 삭감 임박처럼 보이지만 아님; 감가상각은 장부상 비용). 하지만 현실에서 어려운 두 단계는 공시에서 FFO 조정표를 '찾는 것'(비GAAP, 정형데이터에 없고 보충자료/8-K 첨부나 10-K 깊숙이 묻힘)과 AFFO용 '올바른' 경상자본지출 줄을 집는 것 — 자본지출은 표기가 일관되지 않고 AFFO 표준 공식이 없어 잘못된 줄이 커버리지를 조용히 왜곡함. 거시 함정은 금리 민감도: '인플레 헤지' 리츠도 금리 급등 시 크게 하락(2022)." },
  },
  "options-income": {
    id: "options-income",
    title: "Covered Call — Sell Rent on 100 Shares You Own",
    what: { en: "You own 100 shares; you SELL (write) one call at a strike above today's price, collect the premium now, and agree to sell your shares at the strike if the stock finishes above it. Income with a capped upside — not a hedge.", ko: "100주를 보유한 상태에서 현재가보다 높은 행사가의 콜 1계약을 매도(write)해 프리미엄을 지금 받고, 만기에 주가가 행사가 위면 그 가격에 주식을 넘긴다. 상승이 제한된 인컴이지 헤지가 아니다." },
    steps: { en: ["1. Own (or buy) exactly 100 shares of a stock you're content to sell at your strike.", "2. Open the broker OPTION CHAIN for that ticker; pick an EXPIRATION tab (~30-45 days out).", "3. In the CALL side, pick a strike ABOVE spot (OTM). Read the BID (what you receive), ASK, and the IV column.", "4. Income = BID x 100 (never the mid the model shows). Yield for the period = premium / spot. Check IV isn't fat because of upcoming earnings.", "5. Order ticket: SELL TO OPEN, 1 contract, that strike/expiry, mark it COVERED, LIMIT price = bid (or mid), review the credit, submit.", "6. At expiry: below strike = keep shares + premium (sell another); above strike = shares called away at strike, you keep premium + gain to strike only."], ko: ["1. 행사가에 팔아도 괜찮은 종목을 정확히 100주 보유(또는 매수)한다.", "2. 증권사 옵션 체인을 열고 만기 탭(약 30~45일)을 고른다.", "3. 콜 쪽에서 현재가보다 높은(OTM) 행사가를 고르고 BID(내가 받는 값)·ASK·IV 열을 읽는다.", "4. 수입 = BID x 100 (모형 중간값 아님). 기간 수익률 = 프리미엄 / 현재가. 실적 발표로 IV가 부푼 건 아닌지 확인.", "5. 주문표: 매도(Sell to Open) 1계약, 해당 행사가/만기, '커버드' 표시, 지정가=BID, 받을 크레딧 확인 후 제출.", "6. 만기: 행사가 아래=주식·프리미엄 유지(다음 콜 매도), 행사가 위=행사가에 콜어웨이, 프리미엄+행사가까지 이익만 챙김."] },
    data: { en: ["Premium you RECEIVE — broker option chain, the BID column of the call row at your strike (NOT last, NOT the ask, NOT a model mid). Multiply by 100.", "Strike & expiration — the chain's row (strike) and top expiration tabs.", "IV — the chain's IV / 'Impl Vol' column; spike vs. normal tells you if a known event (earnings) is priced in.", "Bid-ask spread — ask minus bid on that row; wide = illiquid, your fill is worse.", "Real strategy track record — CBOE BXM dashboard (cboe.com/us/indices/dashboard/bxm) vs SPY: buy-write lags in bulls (~8.5% vs ~11%), calmer ride.", "Options approval tier — broker account settings; a covered call needs the lowest tier, but you must apply first (plain stock accounts can't sell calls)."], ko: ["받는 프리미엄 — 증권사 옵션 체인에서 해당 행사가 콜 행의 BID 열(체결가·ASK·모형 중간값 아님). x100.", "행사가·만기 — 체인의 행(행사가)과 상단 만기 탭.", "IV — 체인의 IV/'내재변동성' 열; 평소 대비 급등이면 실적 등 이벤트가 반영된 것.", "호가 스프레드 — 그 행의 ASK - BID; 넓으면 유동성 낮고 체결이 불리.", "실제 성과 기록 — CBOE BXM 대시보드 vs SPY: 상승장에서 뒤처짐(~8.5% vs ~11%), 대신 잔잔.", "옵션 승인 등급 — 증권사 계좌 설정; 커버드 콜은 최저 등급이지만 먼저 신청해야 함(일반 주식 계좌로는 콜 매도 불가)."] },
    rules: { en: ["PASS: you own 100 shares AND would gladly sell them at the strike AND accept missing all gains above it.", "PASS: premium is meaningful vs. spot for the period, and the ask-bid spread is tight.", "FAIL: you'd be upset to lose the shares at the strike — wrong strike or wrong stock.", "FAIL: the premium is fat only because IV is pumped for an earnings/event you're now exposed to.", "FAIL: you're treating it as downside protection — a 2% premium won't save a 30% drop."], ko: ["합격: 100주 보유 AND 행사가에 팔아도 기쁨 AND 그 위 상승 포기를 수용.", "합격: 프리미엄이 기간 대비 의미 있고 ASK-BID 스프레드가 좁음.", "불합격: 행사가에 주식을 잃기 싫음 — 행사가나 종목이 틀림.", "불합격: 이제 노출된 실적/이벤트로 IV가 부풀어 프리미엄만 두툼함.", "불합격: 하락 방어로 착각 — 2% 프리미엄은 30% 하락을 못 막음."] },
    pitfall: { en: "The 100x multiplier and 'you receive the BID, not the mid': a '$2.00' call is $200 of real cash, but you actually collect the chain's BID after the spread — and one contract obligates ALL 100 shares. Get the multiplier or the bid/mid distinction wrong and every income number is off. And a fat premium is a risk WARNING (high IV = the market expects trouble), never a free lunch.", ko: "100배 승수와 '받는 건 중간값이 아니라 BID': '$2.00' 콜은 실제 $200이지만 스프레드 뒤 체인의 BID만큼만 받고, 1계약은 100주 전부를 묶는다. 승수나 BID/중간값을 틀리면 모든 수입 숫자가 어긋난다. 두툼한 프리미엄은 공짜가 아니라 위험 경고(높은 IV = 시장이 문제를 예상)다." },
  },
  "active-trading": {
    id: "active-trading",
    title: "Risk-First Position Sizing (ATR stop, size, expectancy)",
    what: { en: "A survival framework for active/technical trading: decide your loss BEFORE your entry, let volatility set the stop and the stop set the size, and judge the system on expectancy over many trades — fits a disciplined, rule-following trader who accepts being wrong often.", ko: "능동적·기술적 트레이딩을 위한 생존 프레임워크: 진입보다 손실을 먼저 정하고, 변동성이 손절을, 손절이 포지션 크기를 정하게 하며, 개별 거래가 아니라 여러 거래의 기대값으로 시스템을 판단한다 — 자주 틀려도 규율을 지키는 트레이더에게 맞는다." },
    steps: { en: ["1. Pull the name's daily candles (Open/High/Low/Close) and read the last ~15 days off a quote site's Historical Data table (use Adjusted Close, split/dividend-adjusted).", "2. Compute ATR(14) by hand: for each day True Range = max(High−Low, |High−PrevClose|, |Low−PrevClose|); ATR = 14-day average of TR, then smoothed = (priorATR×13 + TR)/14. Sanity-check it's ~1–3% of price, not 10x off.", "3. Set the stop from volatility, before entry: stop = entry − (1.5 to 3 × ATR). Never widen it later.", "4. Size it: risk-$ = account × risk% (1%); stop-distance = entry − stop; shares = risk-$ ÷ stop-distance, rounded DOWN. Recompute risk-$ off your CURRENT balance each trade.", "5. Set a target at ≥2R (2 × stop-distance above entry) so break-even win rate is low; optionally scale out and trail the rest with a Chandelier Exit (22-day high − 3×ATR).", "6. Log every trade in R (−1R stop-out, +2R win); after ~30 trades compute expectancy. If negative, fix the edge — do NOT trade bigger."], ko: ["1. 종목의 일간 캔들(시가/고가/저가/종가)을 시세 사이트 'Historical Data(일별 시세)' 표에서 최근 약 15일 읽는다(분할·배당 반영된 수정종가 사용).", "2. ATR(14)를 손으로 계산: 매일 실질범위 TR = max(고가−저가, |고가−전일종가|, |저가−전일종가|); ATR = TR의 14일 평균, 이후 = (직전ATR×13 + TR)/14. 값이 주가의 약 1~3%인지 검산.", "3. 진입 전에 변동성으로 손절 설정: 손절 = 진입 − (1.5~3 × ATR). 나중에 절대 넓히지 않는다.", "4. 사이징: 위험금액 = 계좌 × 위험%(1%); 손절거리 = 진입 − 손절; 주식수 = 위험금액 ÷ 손절거리, 내림. 매 거래마다 '현재' 잔고로 위험금액 재계산.", "5. 목표는 2R 이상(진입 위로 손절거리의 2배)으로 잡아 손익분기 승률을 낮춘다; 선택적으로 분할 청산하고 나머지는 샹들리에 청산(22일 고가 − 3×ATR)으로 추적.", "6. 모든 거래를 R로 기록(손절 −1R, 승리 +2R); 약 30거래 후 기대값 계산. 음수면 엣지를 고쳐라 — 절대 크게 걸지 마라."] },
    data: { en: ["Daily OHLCV candles: quote site's 'Historical Data' table (e.g. Yahoo Finance /quote/TICKER/history). Use the Adj Close column — adjusted for splits/dividends.", "ATR: NOT printed on the quote page — you compute it from the High/Low/Close columns via the True Range formula (or read it off a charting tool's ATR(14) indicator).", "Entry price: the current/last price on the quote page. Stop distance in $ = entry − stop; risk% and account size are YOUR inputs, not from any filing.", "Everything else (position size, expectancy, R-multiples, break-even win rate) is arithmetic you do on those inputs — no data feed needed."], ko: ["일간 OHLCV 캔들: 시세 사이트 'Historical Data(일별 시세)' 표(예: Yahoo Finance /quote/티커/history, 국내는 네이버 금융·증권사 일별 시세). Adj Close(수정종가) 열 사용.", "ATR: 시세 페이지에 안 나옴 — 고가/저가/종가 열에서 실질범위 공식으로 직접 계산(또는 차트 도구의 ATR(14) 지표로 읽음).", "진입가: 시세 페이지의 현재가/마지막 가격. 손절거리($) = 진입 − 손절; 위험%와 계좌 규모는 재무제표가 아니라 '당신'의 입력값.", "나머지(포지션 크기·기대값·R멀티플·손익분기 승률)는 그 입력값으로 하는 산수 — 데이터 피드 불필요."] },
    rules: { en: ["Risk ≤1% of account per trade (0.5% if nervous) — sized so 10 straight losses leave ~90% of capital (0.99^10).", "Stop = 1.5–3 × ATR; tighter than ~1.5×ATR gets you whipsawed by normal noise.", "Demand reward-to-risk ≥ 2:1 — break-even win rate = 1/(1+R:R), so at 2:1 you only need to win 33%.", "Positive EXPECTANCY, not win rate, is the game: (win%×avgWin) − (loss%×avgLoss) > 0. A 40% win rate with 3:1 wins beats a 70% win rate with tiny wins.", "Recovery is asymmetric: a 50% drawdown needs a 100% gain to recover — this is WHY risk stays at 1%."], ko: ["거래당 위험 ≤ 계좌의 1%(불안하면 0.5%) — 10연패해도 자본의 약 90%가 남도록(0.99^10) 사이징.", "손절 = 1.5~3 × ATR; 약 1.5×ATR보다 좁으면 정상 잡음에 털린다(휩쏘).", "손익비 ≥ 2:1 요구 — 손익분기 승률 = 1/(1+손익비), 2:1이면 33%만 이겨도 된다.", "승률이 아니라 양(+)의 기대값이 핵심: (승률×평균이익) − (패율×평균손실) > 0. 이익이 3배면 40% 승률이 이익 작은 70% 승률을 이긴다.", "회복은 비대칭: 50% 손실은 회복에 100% 상승이 필요 — 그래서 위험을 1%로 유지한다."] },
    pitfall: { en: "The lab hands you frozen entries and auto-computes ATR, so the two things you must supply on a REAL trade — a genuine setup/entry and today's ATR read or computed off a live chart — are the exact steps never rehearsed in the tool; and every result is a tiny past-data sample, so add commissions, slippage, and overnight-gap risk (a gap can blow through your stop and lose more than your 1%) before trusting any expectancy number.", ko: "랩은 고정된 진입을 주고 ATR를 자동 계산하므로, 실제 거래에서 당신이 직접 공급해야 하는 두 가지 — 진짜 셋업/진입과 라이브 차트에서 읽거나 계산한 오늘의 ATR — 가 바로 도구에서 연습되지 않는 단계다. 또 모든 결과는 작은 과거 표본이므로, 어떤 기대값도 믿기 전에 수수료·슬리피지·밤사이 갭 위험(갭이 손절을 뚫어 1%보다 더 잃을 수 있음)을 더하라." },
  },
};

export function getCheatsheet(id: string): Cheatsheet | null {
  return CHEATSHEETS[id] ?? null;
}
